### ISSUE TITLE
Do not track user's location with LocationManager

### ISSUE THREAD

**Issue by alan-rodriguez** [Marketo/android-sdk#10]
The [LOCATION](https://developer.android.com/reference/android/Manifest.permission_group.html#LOCATION) is classified as a dangerous permission group by Android and therefore requires a permission prompt for targetSdkVersion 23 and higher. Regardless,  collecting information about the user's location is a highly offensive practice for applications that do not incorporate location into their functionality. There is no need for Marketo to attempt to collect location information by default.

**Comment by jrudydev** [comment]
This has been removed. The SDK is not using this permission and is also not in the official Marketo mobile docs.
