### ISSUE TITLE
Proguard issue

### ISSUE THREAD

**Issue by dorozhans** [Marketo/android-sdk#14]
Hi, I'm using proguard with Marketo version 0.7.7 and after adding this library to my project I can't make a build 'cause I have some troubles with proguard. I've added these lines to rules:
-dontwarn com.marketo.*
-dontnote com.marketo.*
-keep class com.marketo.**{ *; }

But it's not enough as I see. Also, I don't know what is an error here and how fix it, could you review it?
The first one is output without Marketo. The second one - when marketo is in the project.
1. https://prnt.sc/li86ix
2. http://prntscr.com/li886h

**Comment by dorozhans** [comment]
The main differrence that I've found is:
Note: marketo.b.a: can't find dynamically referenced class android.os.SystemProperties

**Comment by pandemanish** [comment]
@dorozhans We have tested many scenarios where we added the Marketo [Android SDK 0.7.7](https://github.com/Marketo/android-sdk/tree/0.7.7) & [0.7.8 (latest)](https://github.com/Marketo/android-sdk/tree/0.7.8) and added [Pro-guard settings ](https://github.com/Marketo/android-sdk#proguard-configuration-optional) and were able to generate APK without any issue. Can you please provide more detailed logs on this Issue?

**Comment by pandemanish** [comment]
Closing due to no response
