### ISSUE TITLE
Marketo SDK 0.8.4 

### ISSUE THREAD

**Issue by vincentcastagna** [Marketo/android-sdk#19]
Hello ! 

I see in the README of this repository that the latest release here is 0.8.2. From what I see on maven repository, you have shipped a version 0.8.4. However I can't download it on maven repository https://mvnrepository.com/artifact/com.marketo/MarketoSDK/0.8.4, throws a 403 forbidden ! 

Could you light me on this, I would like to take the latest aar. 

Thanks.

**Comment by vincentcastagna** [comment]
Up ! @mbijapur @skharemarketo

**Comment by glo40610** [comment]
@vincentcastagna Please check now.

**Comment by vincentcastagna** [comment]
@glo40610  

Thanks for your answer. However, still got a 403 ? 

![image](https://user-images.githubusercontent.com/15191066/112156648-d21a8d00-8bbc-11eb-988e-d16c6bd8087d.png)

**Comment by glo40610** [comment]
It is available on GitHub https://github.com/Marketo/android-sdk and Gradle - implementation 'com.marketo:MarketoSDK:0.8.4'

**Comment by vincentcastagna** [comment]
Thank you very much !

**Comment by vincentcastagna** [comment]
@glo40610  Do you know if the target version still 9.0 or 10.0 for 0.8.4 ? What I saw is min is 21

**Comment by glo40610** [comment]
@vincentcastagna Target Version is the latest Android 11 (Recommended to target the latest version of Android). Yes Marketo supports from 21 (minimum version)
