### ISSUE TITLE
Marketo android SDK Failed to init

### ISSUE THREAD

**Issue by ahnjac** [Marketo/android-sdk#20]
Hi all, first time connecting to android Marketo 0.8.6

I am getting an IOException, 'failed to initialize MarketoSDK 0.8.6 IOException'

Munchkin ID: 824-XEX-790.

I have read on iOS Side that initialization fails because the Marketo subscription is not set up correctly? 

Thank you

**Comment by ahnjac** [comment]
Could this be a TargetedSDK issue?

**Comment by PhaniParvathaneni** [comment]
Any update on this issue ?

**Comment by mbijapur** [comment]
Hi @ahnjac / @PhaniParvathaneni - This seem to be a provisioning issue, as mentioned you will have to get in touch with your Marketo executive for your account, they should be able to help you to check and enable Mobile feature on your Marketo subscription. 

Meanwhile to speed-up the process I've already created an internal ticket to a concerned team. Thank you for your patience.

Thanks
Mahesh
