### ISSUE TITLE
The app still receive notification when the function uninitializeMarketoPush is called

### ISSUE THREAD

**Issue by QuocNamIT1** [Marketo/android-sdk#21]
Hello everyone,
I'm using Marketo SDK to push notifications for my React Native project. I have an issue when the user logout, uninitializeMarketoPush of SDK is called, and I saw logs from Makero SDK: 'Unregistered device from FCM'. But when I push a notification from Marketo admin
, the app still receives a notification.
You can see my screenshot below.

OS: Android
Version: 11

<img width="1690" alt="Screenshot 2023-10-24 at 15 46 06" src="https://github.com/Marketo/android-sdk/assets/12660825/dc7a5e68-3208-4393-9a50-5387ca144135">
<img width="399" alt="Screenshot 2023-10-24 at 15 46 55" src="https://github.com/Marketo/android-sdk/assets/12660825/a76326b6-4dba-4041-996a-195b30ebd5e3">

**Comment by mbijapur** [comment]
Hi @QuocNamIT1 

Regret the inconveniences caused due to this issue. To further investigate this I request you to reach out to the Marketo support, you can share specific details so that we will take a better look at the issue.

Also, I request you to please close this issue.
