### ISSUE TITLE
Getting the same error from MKTO, failed to initialize MarketoSDK 0.8.9 IOException

### ISSUE THREAD

**Issue by jason0404** [Marketo/android-sdk#23]
Failed to initialize for the Android sdk, please support as soon as possible. As when i went through your customer support care. It won't even connect me to the support agent.

**Comment by jason0404** [comment]
![Uploading image.png…]()

**Comment by jason0404** [comment]
![image](https://github.com/Marketo/android-sdk/assets/52486115/163382bf-0289-47b5-9ff4-c1a9c62bbfc8)

**Comment by jason0404** [comment]
<img width="480" alt="Screenshot 2024-03-05 at 2 16 45 PM" src="https://github.com/Marketo/android-sdk/assets/52486115/a72f72d8-d4f9-4ddb-a055-c2901001056c">
Same goes to 0.8.11

**Comment by Santhosh-Umapathi** [comment]
Hi @jason0404 , Could you provide the setup for this on React Native Android. The document is outdated and not really helpful.

**Comment by kaushik-patel-us** [comment]
I have investigated the issue with initializing the MarketoSDK in the RNMarketoModule.kt file and identified a mismatch in the function parameters of initializeSDK.

Issue Details:

Problem: The initializeSDK function has parameter mismatches which result in an IOException during SDK initialization.
Solution:

To resolve this issue, update the initializeSDK function in RNMarketoModule.kt as follows:

@ReactMethod
fun initializeSDK(munchkinId: String, appSecreteKey: String, frameworkType: String) {
    marketoSdk.initializeSDK(frameworkType, munchkinId, appSecreteKey)
}

**Comment by sandy1198** [comment]
what are the frameworkType is  there anyone listed out please

**Comment by mbijapur** [comment]
Hi @sandy1198 
It is documented in the release and developer document, frameworkType is a parameter to capture the type of framework used for development. You can use,
**native** for - Native iOS or Android App
**reactNative** for ReactNative App
**ionic** for Ionic App
**phonegap** for PhoneGap App
