### ISSUE TITLE
Unable to Get Firebase server key  

### ISSUE THREAD

**Issue by sandy1198** [Marketo/android-sdk#24]
I was following this document to setup push notification 

[documentation link here ](https://experienceleague.adobe.com/en/docs/marketo/using/product-docs/mobile-marketing/admin/configure-mobile-app-android-push-access)

But in step 5 I try to navigate Google Firebase console for the server key but they were legacy that server key 

![image](https://github.com/user-attachments/assets/1a356c53-95da-4107-8434-a792e2ede9ae)

any new way to get that server please let me know

**Comment by sandy1198** [comment]
Any update guys ?

**Comment by mbijapur** [comment]
Hi @sandy1198 
Regret the inconveniences caused due to this issue, please use https://experienceleague.adobe.com/en/docs/marketo-developer/marketo/mobile/push-notifications#setup-push-notification-on-android to configure push notifications for Android.

You can get server key from your Firebase Console only.

**Comment by sandy1198** [comment]
Hi @mbijapur any update on the Phonegap plugin Android platform 
![image](https://github.com/user-attachments/assets/429c83ae-8bf2-4477-a68c-6b16dde4a2e8)
where we have to upload json file exactly
https://github.com/Marketo/PhoneGapPlugin
please support, 
I can't raise issue in that repo but same Android SDK only using there too

**Comment by mbijapur** [comment]
Hi @sandy1198 
You need to Enable MME FCM HTTPv1 in Marketo feature manager as we explained in the previous link, then instead of above UI you can see option to upload json file.
If you need more help you can raise a support ticket.
