### ISSUE TITLE
SDK is incompatible with Android SDK 23

### ISSUE THREAD

**Issue by LazyDave76** [Marketo/android-sdk#3]
I have added the Marketo android SDK to our app. When minifying the app through ProGuard, I notice that the app is now failing to build as it using a deprecated android method:

Warning:marketo.push.a: can't find referenced method 'void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)' in library class android.app.Notification

**Comment by kodeshpa** [comment]
Hi,

We have fixed this issue. We were using Notification class directly but Android restricts to use Notification.Builder above honeycomb, hence it was giving this error. Please pull the latest version and try now.
