### ISSUE TITLE
Add Marketo SDK to JCenter and/or MavenCentral

### ISSUE THREAD

**Issue by cassgenerator** [Marketo/android-sdk#6]
Downloading and adding an AAR to the project works fine. However it would be much more convenient and quick to get set up if it was added to JCenter and/or MavenCentral so that we could just add one line to a Gradle build file to add the Marketo library.

Could we please have builds deployed to JCenter and/or MavenCentral?

**Comment by alan-rodriguez** [comment]
If you want customers with Android apps to take your product seriously, properly deploying your Android SDK is a must.

**Comment by jrudydev** [comment]
Gradle support will be available in the next release.

**Comment by pandemanish** [comment]
We have provided Gradle support for Marketo Library in its [Preprod branch](https://github.com/Marketo/android-sdk/tree/preprod)
Please follow the steps provided in the [ReadMe ](https://github.com/Marketo/android-sdk/blob/preprod/README.md)
