### ISSUE TITLE
Use ActivityLifecycleCallbacks instead of imposing onStart/onStop ceremony on all Activities

### ISSUE THREAD

**Issue by alan-rodriguez** [Marketo/android-sdk#8]
It doesn't seem that there is any real need to impose the requirement that all consumers of this SDK perform the [following ceremony](http://developers.marketo.com/mobile/installation/#android_initialize_sdk) on every Activity in their Application:

> 2. Configure activities. Add Marketo.onStart, Marketo.onStop in all or in base activity as shown below.

This burden can removed from SDK consumers if the Marketo SDK uses [Application.ActivityLifecycleCallbacks](https://developer.android.com/reference/android/app/Application.ActivityLifecycleCallbacks.html) to do whatever work is necessary in onStart and onStop.

**Comment by jrudydev** [comment]
The SDK currently supports API Level 8 for push notifications. Once we decide to stop supporting the lower APIs we can implement this. It is already implemented for InApp messaging(API Level 14).

**Comment by pandemanish** [comment]
Marketo SDK is already using ActivityLifecycleCallbacks but the Callback functions were provided if the user specifically wanted to record some additional information
