### ISSUE TITLE
Set targetSdkVersion in AndroidManifest.xml

### ISSUE THREAD

**Issue by alan-rodriguez** [Marketo/android-sdk#9]
There is no way to tell what SDK version this library is written against because `android:targetSdkVersion` is not set in the AAR's AndroidManifest.xml.

**Comment by jrudydev** [comment]
This is already in the AndroidManifest.xml. We will update the documentation to clarify the minimum supported API.

**Comment by alan-rodriguez** [comment]
Here are the contents of the AndroidManifest.xml that is included in your AAR here: https://github.com/Marketo/android-sdk/blob/preprod/marketo/Marketo-release.aar

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.marketo"
    android:versionCode="1"
    android:versionName="1.0" >

    <uses-sdk android:minSdkVersion="14" />

    <application android:allowBackup="true" />

</manifest>
```

The android:targetSdkVersion attribute is still missing from the uses-sdk node. You may targeting Oreo internally but it is not carrying over to the AAR.

**Comment by pandemanish** [comment]
We have added Support for Android P and minimum supported SDK version is set to 14.
Please Follow the developer [documentation](http://developers.marketo.com/mobile), if you are already a customer please contact[ Marketo Customer Support](https://www.marketo.com/why-marketo/services-and-support/support/).
